import type { Product } from "../types/Product";

export const mockAccessories: Product[] = [
  {
    id: "ACC-001",
    name: "Mica de Vidrio Templado Universal",
    code: "MICA-UNI",
    imei: "N/A",
    price: 5,
    stock: 200,
    image: "https://images.unsplash.com/photo-1583225214464-9296029427aa",
    category: "accessories",
    description: "Protección resistente contra golpes y rayones",
  },
  {
    id: "ACC-002",
    name: "Mica de Vidrio Templado Full Cover",
    code: "MICA-FULL",
    imei: "N/A",
    price: 7,
    stock: 180,
    image: "https://images.unsplash.com/photo-1603899123005-4d8d9d7a9c52",
    category: "accessories",
    description: "Cobertura completa de pantalla",
  },
  {
    id: "ACC-003",
    name: "Audífonos Bluetooth In-Ear",
    code: "AUD-BT-01",
    imei: "N/A",
    price: 18,
    stock: 120,
    image: "https://images.unsplash.com/photo-1585386959984-a41552231693",
    category: "accessories",
    description: "Sonido estéreo y batería de larga duración",
  },
  {
    id: "ACC-004",
    name: "Audífonos Bluetooth Deportivos",
    code: "AUD-SPORT",
    imei: "N/A",
    price: 22,
    stock: 90,
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df",
    category: "accessories",
    description: "Ideales para ejercicio, resistentes al sudor",
  },
  {
    id: "ACC-005",
    name: "Cargador Rápido 20W USB-C",
    code: "CARG-20W",
    imei: "N/A",
    price: 15,
    stock: 100,
    image: "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6",
    category: "accessories",
    description: "Carga rápida compatible con múltiples marcas",
  },
  {
    id: "ACC-006",
    name: "Cargador Rápido 33W",
    code: "CARG-33W",
    imei: "N/A",
    price: 20,
    stock: 80,
    image: "https://images.unsplash.com/photo-1621939514649-280e2ee25f23",
    category: "accessories",
    description: "Mayor potencia para carga express",
  },
  {
    id: "ACC-007",
    name: "Cable USB-C Reforzado",
    code: "CAB-USBC",
    imei: "N/A",
    price: 6,
    stock: 300,
    image: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0",
    category: "accessories",
    description: "Cable resistente de carga y datos",
  },
  {
    id: "ACC-008",
    name: "Cable Lightning Certificado",
    code: "CAB-LIGHT",
    imei: "N/A",
    price: 10,
    stock: 140,
    image: "https://images.unsplash.com/photo-1611734827279-2a78b85d59d6",
    category: "accessories",
    description: "Compatible con dispositivos Apple",
  },
  {
    id: "ACC-009",
    name: "Power Bank 10.000mAh",
    code: "PB-10000",
    imei: "N/A",
    price: 25,
    stock: 70,
    image: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5",
    category: "accessories",
    description: "Carga portátil para viajes y emergencias",
  },
  {
    id: "ACC-010",
    name: "Power Bank 20.000mAh",
    code: "PB-20000",
    imei: "N/A",
    price: 38,
    stock: 50,
    image: "https://images.unsplash.com/photo-1612815155133-c8c5f1db517a",
    category: "accessories",
    description: "Alta capacidad para múltiples cargas",
  },
  {
    id: "ACC-011",
    name: "Parlante Bluetooth Portátil",
    code: "PARL-BT",
    imei: "N/A",
    price: 35,
    stock: 45,
    image: "https://images.unsplash.com/photo-1585386959984-a41552231693",
    category: "accessories",
    description: "Sonido potente y conexión inalámbrica",
  },
  {
    id: "ACC-012",
    name: "Parlante Bluetooth Resistente al Agua",
    code: "PARL-WATER",
    imei: "N/A",
    price: 45,
    stock: 30,
    image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f",
    category: "accessories",
    description: "Ideal para exteriores y piscina",
  },
  {
    id: "ACC-013",
    name: "Case Protector Transparente",
    code: "CASE-TPU",
    imei: "N/A",
    price: 7,
    stock: 200,
    image: "https://images.unsplash.com/photo-1606813909359-dc1a9c3e20f4",
    category: "accessories",
    description: "Protección ligera sin perder diseño",
  },
  {
    id: "ACC-014",
    name: "Case Antigolpes Reforzado",
    code: "CASE-ARMOR",
    imei: "N/A",
    price: 12,
    stock: 120,
    image: "https://images.unsplash.com/photo-1606813909359-dc1a9c3e20f4",
    category: "accessories",
    description: "Máxima protección contra caídas",
  },
  {
    id: "ACC-015",
    name: "Soporte Magnético para Auto",
    code: "SOP-AUTO",
    imei: "N/A",
    price: 9,
    stock: 160,
    image: "https://images.unsplash.com/photo-1611078489935-0cb964de46f9",
    category: "accessories",
    description: "Soporte práctico para conducir",
  },
];
